sudo: false

language: php

php:
    - 8.0
    - 7.4
    - 7.3

install:
  - composer install
  - composer global require behat/behat
  - export PATH=$PATH:$HOME/.config/composer/vendor/bin/

script:
  - vendor/bin/phpunit
  - behat
